/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#313aa0',
        'on-error': '#690005',
        outline: '#908f9e',
        'on-surface-variant': '#c6c5d5',
        'secondary-fixed-dim': '#bdc2ff',
        'secondary-fixed': '#e0e0ff',
        'on-error-container': '#ffdad6',
        'surface-bright': '#3a393a',
        'on-secondary-fixed-variant': '#313aa0',
        'on-primary-fixed-variant': '#2e3aa2',
        'on-surface': '#e5e1e3',
        'on-secondary-container': '#a8afff',
        'on-secondary': '#161f89',
        'on-secondary-fixed': '#000668',
        'on-primary-container': '#fdfaff',
        'tertiary-fixed-dim': '#ffb867',
        error: '#ffb4ab',
        'surface-container-low': '#1c1b1d',
        'primary-container': '#5e6ad2',
        'outline-variant': '#454652',
        'inverse-primary': '#4854bb',
        'tertiary-fixed': '#ffddbb',
        secondary: '#bdc2ff',
        'on-primary': '#121f8b',
        'primary-fixed': '#dfe0ff',
        'on-primary-fixed': '#000965',
        tertiary: '#ffb867',
        'on-tertiary': '#482900',
        'on-background': '#e5e1e3',
        'on-tertiary-container': '#fffaf8',
        'surface-tint': '#bdc2ff',
        'surface-container-lowest': '#0e0e0f',
        'inverse-on-surface': '#313032',
        'tertiary-container': '#a56500',
        'surface-container-high': '#2a2a2b',
        surface: '#131315',
        'primary-fixed-dim': '#bdc2ff',
        'surface-container': '#201f21',
        background: '#131315',
        'inverse-surface': '#e5e1e3',
        'surface-container-highest': '#353436',
        'surface-variant': '#353436',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#673d00',
        'on-tertiary-fixed': '#2b1700',
        primary: '#bdc2ff',
        'surface-dim': '#131315',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'max-width': '1200px',
        base: '4px',
        'margin-desktop': '80px',
      },
      maxWidth: {
        'max-width': '1200px',
      },
      fontFamily: {
        'headline-lg-mobile': [
          'Geist',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'headline-xl': [
          'Geist',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'headline-md': [
          'Geist',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'body-lg': [
          'Inter',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'headline-lg': [
          'Geist',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'body-md': [
          'Inter',
          'PingFang SC',
          'Microsoft YaHei',
          'sans-serif',
        ],
        'label-mono': [
          'Geist',
          'ui-monospace',
          'PingFang SC',
          'sans-serif',
        ],
      },
      fontSize: {
        'headline-lg-mobile': [
          '28px',
          {
            lineHeight: '1.2',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'headline-xl': [
          '48px',
          {
            lineHeight: '1.1',
            letterSpacing: '-0.04em',
            fontWeight: '600',
          },
        ],
        'headline-md': [
          '24px',
          {
            lineHeight: '1.3',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': [
          '32px',
          {
            lineHeight: '1.2',
            letterSpacing: '-0.03em',
            fontWeight: '600',
          },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': [
          '12px',
          { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' },
        ],
      },
      boxShadow: {
        header: '0 0 20px rgba(94,106,210,0.1)',
        indigo: '0 0 32px rgba(94, 106, 210, 0.2)',
      },
    },
  },
  plugins: [],
}
